examples_and_test/patients_behavior_study.py
Update path to data, to match Neurospin work environment.
=> Update path for neurospin.

examples_and_test/patients_behavior_study.py
Compute analysis for the five Z-score language score, based on Laure Drutel interpretation of the NEEL battery test.
=> Compute analysis for the five behavioral language

.idea/ConPagnon.iml, .idea/workspace.xml, examples_and_test/build_results_tables.py, examples_and_test/patients_behavior_study.py
Perform new connectivity analysis, simplify the model, using the Z-score of 5 composite language scores.
=> Perform new connectivity analysis.

.idea/dictionaries/dhaif.xml, .idea/inspectionProfiles/Project_Default.xml, .idea/workspace.xml, examples_and_test/build_results_tables.py, examples_and_test/dti_prepoc.py, examples_and_test/patients_behavior_study.py, examples_and_test/the_power_of_the_tangent_space.py, machine_learning/scores_predictions.py
- Simply diffusion pre-processing
- Clean and test the code: the_power_of_the_tangent_space.py
- Perform other resting state analysis
- Build results table from new resting state analysis
- Correct function from code scores_predictions.py in the machine
learning module.
=> New analysis, cleaning the code.

.idea/dictionaries/dhaif.xml, .idea/workspace.xml, examples_and_test/AFQ_directories.py
bval and bvec were inversed in the code.
=> - AFQ_directories.py: inverse the bval and bvec files

machine_learning/CPM_method.py
Fixed typo, and top commenting.
=> - CPM_method.py: Commenting, fixed typo

.gitignore, sphinx/code.rst
Add CPM method to documentation
=> Documentation completion

sphinx/conf.py
Changing the theme to the more flexible and responsive Sphinx material design.
=> Change theme to Sphinx material

sphinx/code.rst, sphinx/conf.py, sphinx/index.rst, sphinx/projectDescription.rst
Complete new conf file for the new sphinx theme installed.
=> New theme modification

sphinx/conf.py
Change color theme for Red (primary) and Blue (accent). Will match the logo color too.
=> Change Color theme

docs/.buildinfo, docs/_modules/index.html, docs/_modules/plotting/display.html, docs/code.html, docs/genindex.html, docs/index.html, docs/projectDescription.html, docs/py-modindex.html, docs/search.html
New static file with the updated color theme
=> Update all the static file with the new color theme

.idea/inspectionProfiles/Project_Default.xml, LICENSE, computing/compute_connectivity_matrices.py, connectivity_statistics/parametric_tests.py, connectivity_statistics/regression_analysis_model.py, data_handling/atlas.py, docs/examples/index.html, setup.py
Add documentation of some functions.
=> Update documentation with the new pages.

README.rst, setup.cfg
=> Add README.rst

setup.py
Add the download link to the 2.0.0 release !
=> Add the right download_url for PiPy

setup.py
New small release, fixing the dependencies during install.
=> Updated the version of ConPagnon: v2.0.1

.gitignore
=> Prepare the 2.0.2 release:

setup.py
In the setup.py file:
- Use find_packages() from the setuptools modules.
- Remove the __init__.py file at the root of the Github.
=> Prepare the 2.0.3 release

README.rst
=> Prepare the 2.0.3 release:

conpagnon/sphinx/conf.py
- Footer modification on documentation.
=> 2.0.4 release:

setup.py
- Fixed small bug regarding computing connectivity matrices.
=> 2.0.5 release:

setup.py
=> 2.0.6 release:

setup.py
- Fixed pylearn_mulm import into ConPagnon
=> 2.0.7 release:

conpagnon/version.py
- Add version.py, with required modules checking.
=> Prepare 2.0.9:

setup.py
Bug fix when calling __version__
=> Prepare 2.0.10:

setup.py
- Fix __version__ call in setup.py, and version number fetching from version.py.
=> Prepare 2.0.10

conpagnon/__init__.py
- Complete the __init__.py, with __version__ import.
=> Prepare 2.0.11
